# Generated by Django 6.0.5 on 2026-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_snapshot', models.URLField(blank=True, help_text="Snapshot of the candidate's master resume URL at the time of application", max_length=500, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('employer_notes', models.TextField(blank=True, help_text='Private notes for the employer to review the candidate', null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=100)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('location_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g., Adoor, Kerala or Remote', max_length=255, null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Minimum salary limit', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Maximum salary limit', null=True)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive / Director')], default='entry', max_length=20)),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated skills (e.g., Python, Django, React)', max_length=255, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
