# Generated by Django 6.0.5 on 2026-06-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_is_flagged'),
        ('users', '0002_customuser_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Message to the candidate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='users.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='users.employer')),
                ('job', models.ForeignKey(blank=True, help_text='Optional associated job listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
