# Generated by Django 6.0.5 on 2026-07-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_details',
            field=models.JSONField(blank=True, default=dict, help_text='Scoring breakdown by category'),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0, help_text='ATS suitability score (0-100)'),
        ),
    ]
