# Generated by Django 6.0.5 on 2026-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_match_details_application_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_reject_threshold',
            field=models.IntegerField(blank=True, help_text='Auto-reject if match score is below this %', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_shortlist_threshold',
            field=models.IntegerField(blank=True, help_text='Auto-shortlist if match score is above this %', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='must_have_skills',
            field=models.CharField(blank=True, help_text='Comma-separated absolute dealbreakers', max_length=255, null=True),
        ),
    ]
