# Generated by Django 6.0.5 on 2026-07-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_auto_reject_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Recipient email address', max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, help_text='Email body content')),
                ('email_type', models.CharField(blank=True, help_text='E.g. application_submitted, shortlisted, rejected', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the send failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='The application this email relates to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='jobs.application')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
