# Generated by Django 6.0.5 on 2026-07-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged by admin for moderation review'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., Adoor, Kerala or Remote', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='onsite', max_length=20),
        ),
    ]
