# Generated by Django 6.0.5 on 2026-07-12 08:28

import apps.jobs.models
import apps.users.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_application_applied_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF or DOCX (Max 5MB)', null=True, upload_to=apps.jobs.models.secure_resume_upload_path, validators=[apps.users.validators.validate_resume_ext, apps.users.validators.validate_resume_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('ready_for_interview', 'Ready for Interview'), ('interviewing', 'Interviewing'), ('not_picked_up', 'Not Picked Up'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=100),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_picked_up', 'Not Picked Up'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='When the call is scheduled (UTC)', null=True)),
                ('twilio_call_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('transcript', models.TextField(blank=True, help_text='Full conversation transcript')),
                ('ai_score', models.IntegerField(blank=True, help_text='AI interview score 0-100', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated interview summary')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of call attempts made')),
                ('max_retries', models.IntegerField(default=3, help_text='Max call attempts before giving up')),
                ('error_message', models.TextField(blank=True)),
                ('call_duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='jobs.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('interview_not_picked_up', 'Interview Not Picked Up'), ('interview_failed', 'Interview Failed'), ('status_change', 'Status Change')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
