# Generated by Django 6.0.5 on 2026-07-13 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_application_resume_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='transcript_data',
            field=models.JSONField(blank=True, default=list, help_text='Structured JSON transcript: [{"role": "ai"|"candidate", "content": "...", "timestamp": "...", "sequence": N}]'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full conversation transcript (legacy raw text)'),
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Chronological order (1 = first question)')),
                ('text', models.TextField(help_text='The question text generated by the LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='jobs.interviewsession')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('session', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Transcribed candidate speech (Groq Whisper)')),
                ('latency_seconds', models.FloatField(blank=True, help_text='Seconds between AI question finishing and candidate answer arriving', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='jobs.aiquestion')),
            ],
            options={
                'ordering': ['question__sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Twilio CallStatus value (e.g. initiated, ringing, completed)', max_length=30)),
                ('sip_code', models.CharField(blank=True, help_text='SIP response code from Twilio (e.g. 200, 486, 603)', max_length=10)),
                ('carrier_data', models.JSONField(blank=True, default=dict, help_text='Raw Twilio webhook POST payload for full observability')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='jobs.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TELEPHONY_TRIGGER', 'Telephony Trigger'), ('GATEKEEPER_APPROVED', 'Gatekeeper Approved'), ('GATEKEEPER_REJECTED', 'Gatekeeper Rejected'), ('CALL_RETRY', 'Call Retry'), ('CALL_EXHAUSTED', 'Call Attempts Exhausted'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('INTERVIEW_SCORED', 'Interview Scored'), ('STATUS_CHANGE', 'Status Change')], db_index=True, max_length=30)),
                ('reason', models.TextField(help_text='Explicit business logic statement explaining WHY this event happened')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (scores, thresholds, timestamps)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobs.application')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobs.interviewsession')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='The user who initiated the action (null = automated system rule)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
