# Generated by Django 6.0.5 on 2026-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_interviewsession_transcript_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('ready_for_interview', 'Ready for Interview'), ('interviewing', 'Interviewing'), ('interview_completed', 'Interview Completed'), ('not_picked_up', 'Not Picked Up'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='applied', max_length=100),
        ),
    ]
