# Generated by Django 6.0.5 on 2026-06-14 16:33

import apps.users.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYER', 'employer'), ('CANDIDATE', 'candidate'), ('DEFAULT', 'default')], default='CANDIDATE', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_pics/')),
                ('headline', models.CharField(blank=True, help_text='e.g., Full Stack Python Developer', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='A short professional summary')),
                ('skills', models.CharField(blank=True, help_text='e.g., Python, Django, React, Neo4j', max_length=500)),
                ('languages', models.CharField(blank=True, help_text='e.g., English, Malayalam, German', max_length=255)),
                ('education', models.CharField(blank=True, help_text='Highest degree or current study', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('expected_salary', models.PositiveIntegerField(blank=True, help_text='Expected annual salary', null=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Adoor, Kerala', max_length=255)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('master_resume', models.FileField(blank=True, help_text='Upload PDF or DOCX (Max 5MB)', null=True, upload_to='master_resumes/', validators=[apps.users.validators.validate_resume_ext, apps.users.validators.validate_resume_size])),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to personal site or projects like TourEase', null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employer_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='employer_banners/')),
                ('description', models.TextField(blank=True, help_text='Detailed about section for the company')),
                ('industry', models.CharField(choices=[('tech', 'Technology & Software'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='other', max_length=50)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('500+', '500+ Employees')], default='1-10', max_length=20)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, help_text='e.g., Berlin, Germany', max_length=255)),
                ('domain', models.URLField(blank=True, help_text='Company Website', null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
