# Generated by Django 6.0.5 on 2026-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged by admin for moderation review'),
        ),
    ]
