# Generated by Django 6.0.5 on 2026-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYER', 'employer'), ('CANDIDATE', 'candidate'), ('DEFAULT', 'default')], default='CANDIDATE', max_length=20),
        ),
    ]
