# Generated by Django 6.0.5 on 2026-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience_years',
            field=models.FloatField(default=0.0),
        ),
    ]
