# Generated by Django 6.0.5 on 2026-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_website',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='A short professional summary'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, help_text='Highest degree or current study', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, help_text='Expected annual salary', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g., Full Stack Python Developer', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.CharField(blank=True, help_text='e.g., English, Malayalam, German', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Adoor, Kerala', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_resume',
            field=models.FileField(blank=True, help_text='Default resume for quick applies', null=True, upload_to='master_resumes/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to personal site or projects like TourEase', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_pics/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, help_text='e.g., Python, Django, React, Neo4j', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='employer_banners/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('201-500', '201-500 Employees'), ('500+', '500+ Employees')], default='1-10', max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed about section for the company'),
        ),
        migrations.AddField(
            model_name='employer',
            name='domain',
            field=models.URLField(blank=True, help_text='Company Website', null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='headquarters',
            field=models.CharField(blank=True, help_text='e.g., Berlin, Germany', max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology & Software'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
