# Generated by Django 6.0.5 on 2026-07-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_candidate_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged by admin for moderation review'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('EMPLOYER', 'employer'), ('CANDIDATE', 'candidate'), ('DEFAULT', 'default')], db_index=True, default='CANDIDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
