# Generated by Django 6.0.5 on 2026-06-10 14:22

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_created_date_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='master_resume',
            field=models.FileField(blank=True, help_text='Upload PDF or DOCX (Max 5MB)', null=True, upload_to='master_resumes/', validators=[apps.users.validators.validate_resume_ext, apps.users.validators.validate_resume_size]),
        ),
    ]
