# Generated by Django 6.0.5 on 2026-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_flagged_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_interview_time',
            field=models.TimeField(blank=True, help_text='Preferred time for AI interview calls (HH:MM). If blank, system picks next weekday 10 AM.', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA timezone (e.g. Asia/Kolkata, America/New_York)', max_length=50),
        ),
    ]
