# Generated by Django 6.0.5 on 2026-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidate_preferred_interview_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='preferred_interview_time',
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_interview_time_end',
            field=models.TimeField(blank=True, help_text='End of preferred time range (HH:MM).', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_interview_time_start',
            field=models.TimeField(blank=True, help_text='Start of preferred time range (HH:MM).', null=True),
        ),
    ]
