"""
Django settings for jobplatform project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env(
    DEBUG=(bool, False) # Default to False if not found
)

# Read the .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

if not DEBUG:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['yourdomain.com', 'www.yourdomain.com'])
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
else:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security: Set a maximum upload size for the entire server (e.g., 5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880


AUTH_USER_MODEL = 'users.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'rest_framework',
    'apps.jobs',
    'apps.admin_panel',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobplatform.wsgi.application'

#jwt configuration

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    #we use this to intercepts every error before it reaches the user
    'EXCEPTION_HANDLER': 'jobplatform.custom_exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '120/minute'
    }
}


# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # If you are using Vite
    "http://127.0.0.1:5173",
]

# Allow the frontend to send credentials (like authorization headers/cookies)
CORS_ALLOW_CREDENTIALS = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),

}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Add the real SMTP configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# This is what the user will see in their inbox!
DEFAULT_FROM_EMAIL = f"Zecpath ATS <{EMAIL_HOST_USER}>"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─── CACHING CONFIGURATION ─────────────────
# Using LocMemCache for development. For production with multiple
# workers / processes, switch to django-redis:
#   CACHES = {
#       'default': {
#           'BACKEND': 'django_redis.cache.RedisCache',
#           'LOCATION': 'redis://127.0.0.1:6379/1',
#           'OPTIONS': { 'CLIENT_CLASS': 'django_redis.client.DefaultClient' },
#       }
#   }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'zecpath-cache',
        'TIMEOUT': 300,  # Default 5-minute TTL
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    }
}


# ─── CELERY CONFIGURATION ──────────────────
from celery.schedules import crontab

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ─── CELERY BEAT SCHEDULE (Periodic / Cron Tasks) ──────────────────
CELERY_BEAT_SCHEDULE = {
    # 1. Clean up expired / blacklisted JWT tokens every night at midnight
    'cleanup-expired-tokens-nightly': {
        'task': 'apps.users.tasks.cleanup_expired_tokens_task',
        'schedule': crontab(minute=0, hour=0),  # Every day at 00:00
    },
    # 2. Send a weekly "Job Digest" email to candidates every Monday at 9 AM
    'send-job-digest-weekly': {
        'task': 'apps.jobs.tasks.send_job_digest_task',
        'schedule': crontab(minute=0, hour=9, day_of_week='monday'),
    },
    # 3. Check for overdue interviews every hour
    'check-overdue-interviews-hourly': {
        'task': 'apps.jobs.tasks.check_overdue_interviews_task',
        'schedule': crontab(minute=0),  # Every hour at :00
    },
    # 4. Clean up AI interview audio files older than 24h
    'cleanup-old-audio-files-daily': {
        'task': 'apps.jobs.tasks.cleanup_old_audio_files_task',
        'schedule': crontab(minute=0, hour=3),  # 3 AM daily
    },
}


# ─── TWILIO CONFIGURATION ──────────────────
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')
TWILIO_WEBHOOK_SECRET = env('TWILIO_WEBHOOK_SECRET', default='')
NGROK_BASE_URL = env('NGROK_BASE_URL', default='')

# ─── GROQ AI CONFIGURATION ──────────────────
GROQ_API_KEY = env('GROQ_API_KEY', default='')
GROQ_STT_MODEL = 'whisper-large-v3'         # Speech-to-Text
GROQ_LLM_MODEL = 'llama-3.3-70b-versatile'  # Conversational brain

# ─── EDGE TTS CONFIGURATION ──────────────────
EDGE_TTS_VOICE = 'en-US-AriaNeural'
