# Generated by Django 6.0.5 on 2026-06-23 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_employer', 'Approve Employer'), ('block_user', 'Block User'), ('unblock_user', 'Unblock User'), ('flag_user', 'Flag User'), ('unflag_user', 'Unflag User'), ('flag_job', 'Flag Job'), ('unflag_job', 'Unflag Job'), ('remove_job', 'Remove Job'), ('restore_job', 'Restore Job')], help_text='Type of admin action performed', max_length=30)),
                ('target_content_type', models.CharField(choices=[('user', 'User'), ('employer', 'Employer'), ('job', 'Job')], help_text='Type of object the action was performed on', max_length=20)),
                ('target_object_id', models.PositiveIntegerField(help_text='Primary key of the target object')),
                ('description', models.TextField(blank=True, help_text='Human-readable summary of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin at the time of the action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(help_text='The admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
